<a href="https://colab.research.google.com/github/marianassimion/challenge-desinformacao/blob/main/fakenews.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Célula 1 — baixar os dois repositórios

In [112]:
!git clone -q https://github.com/roneysco/Fake.br-Corpus.git
!git clone -q https://github.com/Gabriel-Lino-Garcia/FakeRecogna.git

print("Datasets baixados no ambiente do Colab!")

fatal: destination path 'Fake.br-Corpus' already exists and is not an empty directory.
fatal: destination path 'FakeRecogna' already exists and is not an empty directory.
Datasets baixados no ambiente do Colab!

Célula 2 — importar bibliotecas

In [113]:
import pandas as pd
import os
import glob
import re

from IPython.display import display

Célula 3 — carregar o FakeRecogna

In [114]:
arquivo_fakerecogna = glob.glob(
    "/content/FakeRecogna/**/*.xlsx",
    recursive=True
)[0]

df_recogna = pd.read_excel(arquivo_fakerecogna)

print("FakeRecogna:")
print(df_recogna.shape)
print(df_recogna.columns.tolist())
display(df_recogna.head())
print(df_recogna.columns.tolist())

FakeRecogna:
(11902, 8)
['Titulo', 'Subtitulo', 'Noticia', 'Categoria', 'Data', 'Autor', 'URL', 'Classe']

,Titulo,Subtitulo,Noticia,Categoria,Data,Autor,URL,Classe
0,\n\nArthur Lira fraudou a votação sobre voto i...,Boato – Está comprovado que a votação sobre o ...,bomba lira fraudar o votação brasília explodir...,política,17/08/2021,\nEdgard Matsuki,https://www.boatos.org/politica/arthur-lira-fr...,0
1,WhatsApp agora permite silenciar conversas e g...,"Opção vinha sendo testada no aplicativo, e foi...",o whatsapp liberar quinta-feira atualização ap...,política,23/10/2020 10h02,Por G1,https://g1.globo.com/economia/tecnologia/notic...,1
2,"Com Lula, Bolsonaro e Ciro, Fortaleza vira mic...",NaN,debater propor o cidade o campanha prefeitura ...,política,27/10/2020 04h00,Carlos Madeiro,https://noticias.uol.com.br/eleicoes/2020/10/2...,1
3,Alesp aprova projeto que multa em até R$ 100 m...,NaN,o alesp assembleia legislativo paulo aprovar h...,saúde,10/02/2021 23h56,10/02/2021 23h56,https://noticias.uol.com.br/saude/ultimas-noti...,1
4,\n Não é verdade que Fauci sabia há 15 anos q...,Publicações compartilhadas dezenas de vezes de...,“ fauci aprovar o hidroxicloroquina haver ano ...,saúde,11/08/2020 às 20:45,AFP Austrália,https://checamos.afp.com//nao-e-verdade-que-fa...,0

['Titulo', 'Subtitulo', 'Noticia', 'Categoria', 'Data', 'Autor', 'URL', 'Classe']

Célula 4 — padronizar FakeRecogna

In [115]:
# Padronizar colunas do FakeRecogna

df_recogna = df_recogna.rename(columns={
    "Titulo": "title",
    "Subtitulo": "subtitle",
    "Noticia": "text",
    "Categoria": "category",
    "Data": "date",
    "Autor": "author",
    "URL": "link",
    "Classe": "label"
})

# Padronizar os rótulos
df_recogna["label"] = df_recogna["label"].map({
    0: "fake",
    1: "true"
})

# Identificar a origem
df_recogna["source"] = "FakeRecogna"
df_recogna["language"] = "pt"

print(df_recogna.columns.tolist())
print(df_recogna["label"].value_counts())

['title', 'subtitle', 'text', 'category', 'date', 'author', 'link', 'label', 'source', 'language']
label
fake    5951
true    5951
Name: count, dtype: int64

Célula 5 — carregar o Fake.Br

In [116]:
base = "/content/Fake.br-Corpus/full_texts"

registros = []

for label in ["fake", "true"]:

    pasta = os.path.join(base, label)

    arquivos = glob.glob(
        os.path.join(pasta, "*.txt")
    )

    print(label, len(arquivos))

    for arquivo in arquivos:

        with open(
            arquivo,
            "r",
            encoding="utf-8",
            errors="ignore"
        ) as f:

            texto = f.read().strip()

        registros.append({
            "title": "",
            "subtitle": "",
            "text": texto,
            "category": "",
            "author": "",
            "date": "",
            "link": "",
            "label": label,
            "source": "Fake.Br",
            "language": "pt"
        })

df_fakebr = pd.DataFrame(registros)

print("\nFake.Br:")
print(df_fakebr.shape)

display(df_fakebr.head())

fake 3600
true 3600

Fake.Br:
(7200, 10)

,title,subtitle,text,category,author,date,link,label,source,language
0,,,Cunha tem banco de dados com gastos de deputad...,,,,,fake,Fake.Br,pt
1,,,"Datena manda recado para a Rede Globo: ""Oportu...",,,,,fake,Fake.Br,pt
2,,,"Deputado confessa: ""Não estamos preocupados co...",,,,,fake,Fake.Br,pt
3,,,Nunca antes na história deste país um palestra...,,,,,fake,Fake.Br,pt
4,,,"Mais uma farsa de Lula? A verdade sobre o ""fal...",,,,,fake,Fake.Br,pt

Célula 5.1 - Baixar FACTCK.BR

In [117]:
# 5.1 - Baixar o FACTCK.BR

!git clone -q https://github.com/jghm-f/FACTCK.BR.git /content/FACTCK-BR

import os

for root, dirs, files in os.walk("/content/FACTCK-BR"):
    for file in files:
        print(os.path.join(root, file))

fatal: destination path '/content/FACTCK-BR' already exists and is not an empty directory.
/content/FACTCK-BR/README.md
/content/FACTCK-BR/requirements
/content/FACTCK-BR/FACTCKBR.tsv
/content/FACTCK-BR/LICENSE
/content/FACTCK-BR/update_factckbr.py
/content/FACTCK-BR/.git/description
/content/FACTCK-BR/.git/config
/content/FACTCK-BR/.git/index
/content/FACTCK-BR/.git/HEAD
/content/FACTCK-BR/.git/packed-refs
/content/FACTCK-BR/.git/refs/heads/master
/content/FACTCK-BR/.git/refs/remotes/origin/HEAD
/content/FACTCK-BR/.git/hooks/pre-receive.sample
/content/FACTCK-BR/.git/hooks/fsmonitor-watchman.sample
/content/FACTCK-BR/.git/hooks/pre-push.sample
/content/FACTCK-BR/.git/hooks/pre-rebase.sample
/content/FACTCK-BR/.git/hooks/pre-commit.sample
/content/FACTCK-BR/.git/hooks/prepare-commit-msg.sample
/content/FACTCK-BR/.git/hooks/sendemail-validate.sample
/content/FACTCK-BR/.git/hooks/post-update.sample
/content/FACTCK-BR/.git/hooks/pre-applypatch.sample
/content/FACTCK-BR/.git/hooks/commit-msg.sample
/content/FACTCK-BR/.git/hooks/pre-merge-commit.sample
/content/FACTCK-BR/.git/hooks/applypatch-msg.sample
/content/FACTCK-BR/.git/hooks/push-to-checkout.sample
/content/FACTCK-BR/.git/hooks/update.sample
/content/FACTCK-BR/.git/logs/HEAD
/content/FACTCK-BR/.git/logs/refs/heads/master
/content/FACTCK-BR/.git/logs/refs/remotes/origin/HEAD
/content/FACTCK-BR/.git/objects/pack/pack-870afe4f6b60c5aa539ae3e105474e285be179bc.pack
/content/FACTCK-BR/.git/objects/pack/pack-870afe4f6b60c5aa539ae3e105474e285be179bc.idx
/content/FACTCK-BR/.git/objects/pack/pack-870afe4f6b60c5aa539ae3e105474e285be179bc.rev
/content/FACTCK-BR/.git/info/exclude

Célula 5.2 - Ler FACTCK.BR

In [118]:
# 5.2 - Ler o FACTCK.BR

df_factck = pd.read_csv(
    "/content/FACTCK-BR/FACTCKBR.tsv",
    sep="\t"
)

print("Dimensões:", df_factck.shape)
print("\nColunas:")
print(df_factck.columns.tolist())

display(df_factck.head())

Dimensões: (1313, 9)

Colunas:
['URL', 'Author', 'datePublished', 'claimReviewed', 'reviewBody', 'title', 'ratingValue', 'bestRating', 'alternativeName']

,URL,Author,datePublished,claimReviewed,reviewBody,title,ratingValue,bestRating,alternativeName
0,https://aosfatos.org/noticias/governo-bolsonar...,https:www.aosfatos.org,2019-07-22,Espaço dedicado para os eleitores do Bolsonaro...,Publicações que circulam nas redes sociais vej...,Governo Bolsonaro não suspendeu distribuição d...,1.0,5,falso
1,https://aosfatos.org/noticias/nao-e-miriam-lei...,https:www.aosfatos.org,2019-07-22,Vos apresento a funcionária protegida pela Glo...,Uma foto de um treinamento de defesa contra as...,Não é Miriam Leitão quem segura fuzil ao lado ...,1.0,5,falso
2,https://aosfatos.org/noticias/nao-e-verdade-qu...,https:www.aosfatos.org,2019-07-22,Você sabia que Benedita da Silva já foi embaix...,falsa a informação de que a deputada federal ...,Não é verdade que Benedita da Silva foi embaix...,1.0,5,falso
3,https://aosfatos.org/noticias/nao-e-de-mulher-...,https:www.aosfatos.org,2019-07-18,QUEM A MULHER QUE EMPURROU O PADRE MARCELO ROSSI,Modificada digitalmente para incluir o filtro ...,Não é de mulher que empurrou padre Marcelo Ros...,1.0,5,falso
4,https://aosfatos.org/noticias/e-falso-que-refo...,https:www.aosfatos.org,2019-07-17,As crueldades da Reforma da PrevidênciaPessoas...,Uma publicação que circula nas redes sociais a...,É falso que reforma tira de pessoas com defici...,1.0,5,falso

Célula 5.3 - Preparar o FACTCK.BR

In [119]:
# 5.3 - Preparar o FACTCK.BR

df_factck = df_factck.rename(columns={
    "URL": "link",
    "Author": "author",
    "datePublished": "date",
    "claimReviewed": "claim",
    "reviewBody": "review",
    "title": "title",
    "ratingValue": "rating",
    "bestRating": "best_rating",
    "alternativeName": "label"
})

# Ver os valores de classificação
print("Valores em label:")
print(df_factck["label"].value_counts())

display(df_factck.head())

# 5.4 - Padronizar classificação do FACTCK.BR

df_factck["label_original"] = df_factck["label"]

def classificar_factck(valor):
    valor = str(valor).strip().lower()

    if valor == "falso":
        return "fake"

    if valor == "verdadeiro":
        return "true"

    return None

df_factck["label"] = df_factck["label"].apply(classificar_factck)

# Remover classificações que não são claramente fake ou true
df_factck = df_factck.dropna(subset=["label"])

df_factck["source"] = "FACTCK.BR"
df_factck["language"] = "pt"

print("FACTCK.BR após filtragem:")
print(df_factck["label"].value_counts())

Valores em label:
label
Falso                      615
falso                      328
Verdadeiro                 119
Exagerado                   87
Sem contexto                42
distorcido                  29
Distorcido                  25
Impossível provar           20
Discutível                  12
Subestimado                  6
Ainda é cedo para dizer      6
insustentável                5
Verdadeiro, mas              4
exagerado                    4
De olho                      3
impreciso                    2
outros                       1
verdadeiro                   1
Name: count, dtype: int64

,link,author,date,claim,review,title,rating,best_rating,label
0,https://aosfatos.org/noticias/governo-bolsonar...,https:www.aosfatos.org,2019-07-22,Espaço dedicado para os eleitores do Bolsonaro...,Publicações que circulam nas redes sociais vej...,Governo Bolsonaro não suspendeu distribuição d...,1.0,5,falso
1,https://aosfatos.org/noticias/nao-e-miriam-lei...,https:www.aosfatos.org,2019-07-22,Vos apresento a funcionária protegida pela Glo...,Uma foto de um treinamento de defesa contra as...,Não é Miriam Leitão quem segura fuzil ao lado ...,1.0,5,falso
2,https://aosfatos.org/noticias/nao-e-verdade-qu...,https:www.aosfatos.org,2019-07-22,Você sabia que Benedita da Silva já foi embaix...,falsa a informação de que a deputada federal ...,Não é verdade que Benedita da Silva foi embaix...,1.0,5,falso
3,https://aosfatos.org/noticias/nao-e-de-mulher-...,https:www.aosfatos.org,2019-07-18,QUEM A MULHER QUE EMPURROU O PADRE MARCELO ROSSI,Modificada digitalmente para incluir o filtro ...,Não é de mulher que empurrou padre Marcelo Ros...,1.0,5,falso
4,https://aosfatos.org/noticias/e-falso-que-refo...,https:www.aosfatos.org,2019-07-17,As crueldades da Reforma da PrevidênciaPessoas...,Uma publicação que circula nas redes sociais a...,É falso que reforma tira de pessoas com defici...,1.0,5,falso

FACTCK.BR após filtragem:
label
fake    943
true    120
Name: count, dtype: int64

Célula 6 — Juntar os 3

In [120]:
# 6 - Juntar os 3 datasets

df_final = pd.concat(
    [df_fakebr, df_recogna, df_factck],
    ignore_index=True
)

print("Dimensões do dataset final:", df_final.shape)

print("\nQuantidade por fonte:")
print(df_final["source"].value_counts())

print("\nQuantidade por classificação:")
print(df_final["label"].value_counts())

Dimensões do dataset final: (20165, 15)

Quantidade por fonte:
source
FakeRecogna    11902
Fake.Br         7200
FACTCK.BR       1063
Name: count, dtype: int64

Quantidade por classificação:
label
fake    10494
true     9671
Name: count, dtype: int64

Célula 7 — limpeza

In [107]:
# Remover textos vazios
df["text"] = df["text"].fillna("").astype(str)

df = df[
    df["text"].str.strip() != ""
].copy()

# Limpar espaços
df["text"] = (
    df["text"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

# Padronizar labels
df["label"] = (
    df["label"]
    .astype(str)
    .str.lower()
    .str.strip()
)

# Remover duplicatas exatas
df = df.drop_duplicates(
    subset=["text"]
).copy()

# Data
df["date"] = pd.to_datetime(
    df["date"],
    errors="coerce"
)

print("Depois da limpeza:", df.shape)

Depois da limpeza: (19085, 13)

Célula 8 — criar parâmetros

In [108]:
df["text_length"] = df["text"].str.len()

df["word_count"] = (
    df["text"]
    .str.split()
    .str.len()
)

df["uppercase_words"] = df["text"].apply(
    lambda texto: sum(
        1
        for palavra in texto.split()
        if palavra.isupper() and len(palavra) > 1
    )
)

Célula 9 — verificar a integração

In [109]:
print("TOTAL DE NOTÍCIAS")

print(len(df_final))

print("\nPOR DATASET")

display(df_final["source"].value_counts())

print("\nPOR CLASSIFICAÇÃO")

display(df_final["label"].value_counts())

print("\nFAKE × TRUE POR DATASET")

display(
    pd.crosstab(
        df_final["source"],
        df_final["label"]
    )
)

TOTAL DE NOTÍCIAS
20165

POR DATASET

source
FakeRecogna    11902
Fake.Br         7200
FACTCK.BR       1063
Name: count, dtype: int64

POR CLASSIFICAÇÃO

label
fake    10494
true     9671
Name: count, dtype: int64

FAKE × TRUE POR DATASET

label        fake  true
source
FACTCK.BR     943   120
Fake.Br      3600  3600
FakeRecogna  5951  5951

Célula 10 — primeira análise

In [110]:
comparacao = df.groupby(
    ["source", "label"]
).agg(
    noticias=("text", "count"),
    media_palavras=("word_count", "mean"),
    media_caracteres=("text_length", "mean"),
    media_maiusculas=("uppercase_words", "mean")
).round(2)

display(comparacao)

                   noticias  media_palavras  media_caracteres  \
source      label
Fake.Br     fake       3600          185.89           1117.88
            true       3599         1100.56           6672.65
FakeRecogna fake       5935           68.66            461.04
            true       5951           97.39            688.26

                   media_maiusculas
source      label
Fake.Br     fake               3.73
            true              17.21
FakeRecogna fake               0.00
            true               0.00

Célula 11 - Visualização dos data sets integrados

In [111]:
df_final = pd.concat(
    [df_fakebr, df_recogna, df_factck],
    ignore_index=True
)

from google.colab.data_table import DataTable

DataTable.max_columns = 20
DataTable.max_rows = 100

DataTable(df_final)

Warning: total number of rows (20165) exceeds max_rows (100). Limiting to first (100) rows.